include: package:pedantic/analysis_options.1.11.0.yaml

analyzer:
#  exclude:
#    - lib/l10n/**

  language:
    strict-inference: true

  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
