name: flutter_form_builder
description: This package helps in creation of forms in Flutter by removing the boilerplate code, reusing validation, react to changes, and collect final user input.
version: 5.0.0
homepage: https://github.com/danvick/flutter_form_builder

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  datetime_picker_formfield: ^2.0.0
  dropdown_search: ^0.6.1
  flutter_colorpicker: ^0.4.0
  flutter_chips_input:
    git:
      url: https://github.com/JohnGalt1717/flutter_chips_input.git
      ref: 59a2af053a5aadffc1b2e683f102d11a33512a88
  flutter_datetime_picker: ^1.5.1
  flutter_touch_spin: ^2.0.0-nullsafety.1
  flutter_typeahead: ^3.1.3
  intl: ^0.17.0
  rating_bar: ^0.2.0
  signature: ^4.1.1
  validators: ^3.0.0
  collection: ^1.15.0-nullsafety.4

dependency_overrides:
  flutter_chips_input:
    git:
      url: https://github.com/JohnGalt1717/flutter_chips_input.git
      ref: 59a2af053a5aadffc1b2e683f102d11a33512a88

dev_dependencies:
  flutter_test:
    sdk: flutter

  pedantic: ^1.11.0

flutter:
